env=dev
#base.url=https://talentcentral-dev-v2.altimetrik.com/
base.url=https://www.tutorialspoint.com/selenium/practice/text-box.php
browser=chrome
headless=false
explicit.timeout=20
page.load.timeout=60
script.timeout=30